### ISSUE TITLE
Analyze Build Process

### ISSUE THREAD

**Issue by candyam5522** [eurekaclinical/eureka#148]

**Comment by jsons** [comment]
@arpost If wer are going to use a CDN this is the resource which should have all the JS libs that we currently use:  https://cdnjs.com/
I would prefer to use Google as my first choice, but they only carry the most popular libs.  Let me know your thoughts on using cdnjs.com
Thanks

**Comment by arpost** [comment]
I don't feel the need to use a single CDN for everything. It seems like the maintainers of major libraries have a recommended CDN.

**Comment by jsons** [comment]
@arpost  no problem we will use cdnjs for the lesser known items and Google for the popular(Angular etc...)

**Comment by jsons** [comment]
1) JQuery:  https://code.jquery.com/jquery-2.2.4.min.js
2)AngularJS:  https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js
3)Angular-ui-router: https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.15/angular-ui-router.min.js
4)Angular-messages:  https://cdnjs.cloudflare.com/ajax/libs/angular-messages/1.4.14/angular-messages.min.js
5)tg-angular-validator:  will have to keep local or upgrade from 1.2.7, because cdn does not have exact version
6)Bootstrap:  https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js
7)Angular-ui-tree: https://cdnjs.cloudflare.com/ajax/libs/angular-ui-tree/2.9.0/angular-ui-tree.js
8)Font Awesome:  will need to provide email to get cdn embed code
9)Lodash:  https://cdn.jsdelivr.net/lodash/3.10.1/lodash.min.js
10)Angular Mocks: Will need to download or upgrade https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.1/angular-mocks.js 
11)ng-flow: https://cdnjs.cloudflare.com/ajax/libs/ng-flow/2.7.4/ng-flow-standalone.min.js
12)Angular UI Bootstrap: angular-ui.github.io/bootstrap/ui-bootstrap-tpls-2.4.0.js

**Comment by arpost** [comment]
Those look fine. Please let me know more details on the process for Font Awesome.

**Comment by jsons** [comment]
@arpost  there are CDN's that carry Font Awesome, but FA recommends using there CDN.  To get the CDN code you will have to submit an email address.  I figured you or @candyam5522  email would be more appropriate http://fontawesome.io/get-started/
In the mean time I will use a regular CDN then I can update later

**Comment by arpost** [comment]
Here is the URL:
<script src="https://use.fontawesome.com/5e808755b2.js"></script>

Andrew

**Comment by jsons** [comment]
@arpost thanks!

**Comment by arpost** [comment]
Done.
