### ISSUE TITLE
404 after changing password on password expiration page

### ISSUE THREAD

**Issue by candyam5522** [eurekaclinical/eureka#16]
<img width="1161" alt="screen shot 2016-01-05 at 3 57 47 pm" src="https://cloud.githubusercontent.com/assets/5263886/12127831/79ef039a-b3c7-11e5-936d-5c78864e933a.png">

As can see in the pic, if I clear browser's cookie and cache, the first time I log in (right after using default password to set my own password) will show this error msg page. Tested in Chrome only.

**Comment by candyam5522** [comment]
This may look a minor issue on the local, cause the error cannot be recreated unless I clear the browser’s cache and cookie, so we do not see it that often.

But when I do the vagrant up for vm, for both Oracle and PostgreSQL on centos 6, I can see this error when the first time I login, after changing the default password, it does the same thing, it does not redirect to the homepage, but shows an error page:

192.168.64.205 is for PostgreSQL:
<img width="1416" alt="screen shot 2016-01-27 at 5 26 14 pm" src="https://cloud.githubusercontent.com/assets/5263886/12649315/1bd40d40-c5ac-11e5-83d4-72b2f93abf8c.png">

192.168.64.206 is for Oracle:
<img width="888" alt="screen shot 2016-01-27 at 5 49 01 pm" src="https://cloud.githubusercontent.com/assets/5263886/12649327/2a67c39c-c5ac-11e5-963d-d03509fac6a6.png">

This error is hard to recreate, you either clean cache and cookie on local, re-build an re-run to see it, or create a new vm and vagrant up with Oracle or PostgreSQL to see it, either way takes a lot of time.

**Comment by arpost** [comment]
The issue may be described in http://stackoverflow.com/questions/11790756/redirect-with-jsessionid-path-parameter-results-in-404-error. In the PasswordExpiredFilter, we're calling HttpServletRequest.getRequestURI() to get the URL that the expired password change page should return to. We're passing that URI into a query parameter for the expired password change page. The semicolon might be getting encoded.

**Comment by arpost** [comment]
Take a look at the HttpServletResponse.encodeRedirectURL method. According to the javadoc:

Encodes the specified URL for use in the sendRedirect method or, if encoding is not needed, returns the URL unchanged. The implementation of this method includes the logic to determine whether the session ID needs to be encoded in the URL. Because the rules for making this determination can differ from those used to decide whether to encode a normal link, this method is separated from the encodeURL method.
All URLs sent to the HttpServletResponse.sendRedirect method should be run through this method. Otherwise, URL rewriting cannot be used with browsers which do not support cookies.

**Comment by candyam5522** [comment]
Okay, will do, thanks for the suggestions!

**Comment by arpost** [comment]
We now use encodeRedirectURL for the redirect in question, and we set the session tracking method to COOKIE.
