### ISSUE TITLE
CSS style goes wrong if "Save" button does not work at Cohort Editor page

### ISSUE THREAD

**Issue by candyam5522** [eurekaclinical/eureka#18]
Before fix the function for "Save" button, I noticed that CSS style is wrong if the "Save" button does not work and gives an error msg. Even I closed the error msg, the CSS still not right.

But after I fix the "Save" button problem, I do not see it anymore, because the page is redirect to Cohort Home page.

<img width="1062" alt="screen shot 2016-01-03 at 4 45 30 pm" src="https://cloud.githubusercontent.com/assets/5263886/12150190/64355cb6-b476-11e5-84c9-8bb529003285.png">

**Comment by akalsan** [comment]
Miao mentioned that this behavior is seen when an unexpected exception is thrown and a stacktrace is displayed. we don't have any such known issues now that the stacktrace is displayed. She has fixed the issue for which she saw the stack trace. Also, according to our understanding this behavior will be seen on all eureka pages and not just cohort page when a stacktrace is displayed.  the behavior is not seen when an expected/handled error occurs like pop up message box with "Please ensure that the cohort name is filled out." is displayed

**Comment by arpost** [comment]
We need to understand why unexpected exceptions are messing up the page styling. Try editing the cohort save REST endpoint to always return a 500 error and stack trace.

**Comment by akalsan** [comment]
i was able to reproduce this error and it seems to be an issue across all pages and not just the cohort. Attaching the screenshot from the phenotypes Save workflow. when an unchecked exception is thrown, the exception.getMessage() method gives an html source code (With all html tags) and something in it is causing the css style to change. I explicitly set the text to one of the exceptions and i don't see the css changing behavior at all. 
My thought is that the user need not see the stack trace. we can implement this by logging the stack trace instead of showing it to the user and giving a universal user-friendly message for unchecked exceptions like 'There is an internal error. Please contact the website administrators for more information'.  
Does that sound reasonable?
![screen shot 2016-06-24 at 1 53 29 pm](https://cloud.githubusercontent.com/assets/14340728/16348761/81d624f8-3a22-11e6-98a0-1e428dd2af6c.png)

**Comment by arpost** [comment]
Partly. Yes, it makes sense to log exceptions rather than show them to the user. No, text in a dialog box should not be able to mess up page styling. The latter is a bug that I want fixed.
