### ISSUE TITLE
Compile failure: "appProperties is not defined"

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/eureka#33]
eureka/register/services/register-service.js
  line 20  col 32  'appProperties' is not defined.

  ⚠  1 warning

JSHint failed, fix the issues and rerun task.

**Comment by candyam5522** [comment]
This is an easy fix, I already fixed it. 

But since you changed code in phenotype-service.js by injecting appProperties into PhenotypeService

(PhenotypeService.$inject = ['$http', '$q', 'appProperties'];)

as an additional service, the Jasmine test code(phenotype-service-spec.js) failed, because it does not recognize appProperties. 

I need more time to fix the Jasmine unit test cases since AngularJS Jasmine is new to me.

**Comment by candyam5522** [comment]
Just pulled a request, please review it, thanks!
