### ISSUE TITLE
eureka-services GET /jobs/{id} API is very slow

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/eureka#73]

**Comment by akalsan** [comment]
How do i reproduce this behavior? I tried clicking on the jobs link on the header. The jobId is always null and according to  below code snippet 
if (jobIdStr != null) {	Long jobId;
				try {
					jobId = Long.valueOf(jobIdStr);
				} catch (NumberFormatException ex) {
					throw new ServletException("Query parameter jobId must be a long, was " + jobIdStr);
				}
				job = this.servicesClient.getJob(jobId);
			}else{
				List<Job> jobs = this.servicesClient.getJobsDesc();
				if (!jobs.isEmpty()) {
					job = jobs.get(0);
                                }
}
The jobs/{id} APi is not called. I tried to debug and assign a jobID in the debug mode to execute the first if condition but i did not see the API being very slow. The response was quite immediate. any condition that this behavior is seen?

**Comment by arpost** [comment]
This issue likely comes up after lots of jobs have been run, because that database query is going to retrieve every job ever run. We should retrieve only the first job from the database.

**Comment by akalsan** [comment]
i will try to reproduce this error with creating multiple jobs. The api jobs/{id} does not retrieve every job that is been run. Looking at the etl code- it gets the job where jobid={id}.
However, the above code snippet is from the JoblistServlet class and it never calls the jobs/{id} api since jobIdStr is null. The else condition is run which ends up getting the entire job list. Multiple jobs might slow down loading of the jobs page but not the /jobs/{id} api. i will write a script to add multiple jobs to the database and see if i can find out more.

**Comment by akalsan** [comment]
As expected when i added about 4000+ jobs the job page is loading quite slow-(close to a minute at times) since it is getting all the jobs from the database. the API itself jobs{jobid} is quick. 
I would think trying to run a query like "select max(id) from jobs where userid=x " might be faster. I will work on how to implement that query through hibernate and also how i can fit that into the rest design for jobs resource.

**Comment by arpost** [comment]
I don't think you can rely on max(id) being the most recent job. You need to go by the timestamp.

**Comment by akalsan** [comment]
Sorry max(id) was a mistake. I meant to say Max function. Yes will look more to confirm but mostly the max( time stamp)

**Comment by arpost** [comment]
The jobs table may not have start and stop time columns. If not, please add them.

**Comment by akalsan** [comment]
the jobs table just has the start date and does not have the finished date. The job_events table contains that information. do we want to have that information in the jobs table as well. I implemented the change to fix the issue. the recent job is obtained based on the job created date in the jobs table.

**Comment by arpost** [comment]
Please update the REST APIs wiki page with the new /jobs/latest endpoint.

**Comment by arpost** [comment]
Fixed by adding a new REST endpoint to get the latest job for a user, and moving the logic for getting the latest job to the database.

**Comment by arpost** [comment]
There's a failing unit test that we believe is a result of this merge. It looks like calls to /jobs/status?filter=latest=false respond with a 404 if there are no jobs. /jobs/status returns a list of jobs, so it should return an empty list and a status of 200.

**Comment by akalsan** [comment]
fixed this. Happened due to my change in toQueryParam method in jobFilter which i did at the end. Did not expect it to break anything. Lesson learnt to build after the smallest change! i fixed it and build is successful now. Did a pull request.

**Comment by arpost** [comment]
But isn't latest=false the default value for a filter? The result should be the same whether you pass in latest=false or omit it. The test might pass now, but there's still something wrong with the REST API.

**Comment by arpost** [comment]
In JpaJobDao, the method that is called when you invoke /jobs/status is invoked with a null subquery argument, so the value of the latest filter has no effect. That is another issue with the merge.

**Comment by arpost** [comment]
Check out the JobFilter(String queryString) constructor in JobFilter.java. You are trying to set a boolean variable to null, which doesn't work. I wonder if that has something to do with the 404?
