### ISSUE TITLE
Deprecation warnings during eureka-webapp compile: packages need upgrading

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/eureka#75]
[INFO] [ERROR] npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
[INFO] [ERROR] npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
[INFO] [ERROR] npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
[INFO] [ERROR] npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
[INFO] [ERROR] npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
[INFO] [ERROR] npm WARN deprecated lodash@2.4.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.

**Comment by candyam5522** [comment]
1. upgrade frontend-maven-plugin in eureka-webapp pom.xml, so that all [ERROR] now [WARNING]
2. use gulp-clean-css to replace gulp-minify-css, so "[INFO] [ERROR] npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css" won't show anymore
3. for all graceful-fs and lodash deprecations, are due to internal usages of Node.js and other js frameworks, not eureka directly related problem, so leave them as WARNING info(s) for now
